
server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: spring-boot
  resource: spring-boot
  credentials:
    secret: 6fd1b103-7e2b-4c77-850f-a4b41161667f
  bearer-only: true
  public-client: true

  security-constraints:
    - auth-roles:
      - spring-user
      security-collections:
      - name: 
        patterns:
        - /user/*
    - auth-roles:
      - spring-admin
      security-collections:
      - name: 
        patterns:
        - /user/*
        - /admin/*

logging:
  level:
    org.keycloak: TRACE
